### ISSUE TITLE
missing module + performance issues

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-event-manager#1]
Hi. I say you did a new upload and wanted to try to help you with bug testing, but you are missing an module so it's impossible https://github.com/crysalead-js/dom-event-manager/blob/master/index.js#L1

Are the test cases working without this module?

I had a quick look at the code, and I see performance issues. 

1. https://github.com/crysalead-js/dom-event-manager/blob/master/index.js#L41

   Bind() is a performance killer, and also not supported by PhantomJS.
2. https://github.com/crysalead-js/dom-event-manager/blob/master/index.js#L18

   Not the fastest solution either.

**Comment by jails** [comment]
Looks like there's no missing module: https://github.com/crysalead-js/dom-event-manager/blob/master/package.json#L10

1 - Unless you're creating an application where `.bind()` is called so many times that it become a bottleneck I wouldn't bother. Readability is much more important than sheer performance imo.

2 - I'm using this form to avoid using `.hasOwnProperty()` everywhere. Extending core object is a bad practice but since Javascript allows it I prefer make sure this object won't be "polluted".

**Comment by justmeandtaken** [comment]
I figure it out, but just started to wonder why you using a dependency for event handling - a dependency that also support IE7!! Should have been easier to write the code directly.

Anyway. I tried to get your event management to work, but that was not so easy. I managed to fire a "click" event without nothing happen or no callback worked etc.

As it is just now, I'm backing out from bug testing. Let us see in the future.

**Comment by jails** [comment]
When a wheel exists why not using it ;-) ? And `attachEvent` is not a only a IE <= 8 but also a IE9 thingy. Whenever a HTML document does not start with <!DOCTYPE html> `addEventListener` is not defined in IE9 either. So even if the IE < 10 compatibility is not a top priority, I'm fine to use some legacy features when it doesn't introduce limitations or huge complexity.

No prob, I'll probably add a couple of examples in a couples of days
