### ISSUE TITLE
Room for improvments

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-event-manager#2]
As you know I like your coding syle and code, so I couldn't just let this be. Anyway, I finaly managed to figure out how you are thinking, and got this to work. I like a brain challenge you know! 

Through this research of your code, and console.log analyzes, look at this:

1. An bind default event will be searched for everytime you interact with the virtual Tree you create. This means each of this events can be looked up over 47 times in my case (*mousemove*) !!!! Also when the system checking for existence of this **domLayerNode** it do a crazy many lookups. Can or should this be improved? Add rAF?

2. This piece of code **eventName = "on" + name;** gave me an issue in the eventHandler(). I actually had to remove **on** to get it all to work. What is the purpose of this one?
4. When trying to find an element which matches a delegation, your approach forces selection of every element which matches the selector (potentially expensive), and loop that selection for each depth level in the DOM tree. I'm, right? 
Anyway. It could get pretty suboptimal when the matched selection is large, or the virtual tree huge.
The most optimal way would be to go up in the DOM tree, calling matchesSelector once per level.

4. Your regex are slow, and should be optimized:

Change:

```javascript
/^input$|^select$|^textarea$|^button$/
```
to this:

```javascript
^(?:input|select|textarea|button)$/i,
```

Conlusion. What I see now, and what I understand out of this, again great work!!!

**Comment by jails** [comment]
Glad you share my vision of coding ;-)

1. Indeed all `xxxmove` & `xxxover` are catched on `document.body` which implies a couple of extra unnecessary checks. However this strategy is imo the most advantageous especially for a virtual dom implementation. Indeed on each updates, a correct diffing should also be applied on `events`. A Naive approch would be to bind new events and unbind removed ones. However it's not enough. If an event still exist, it doesn't mean its callback still the same in the new virtual tree. So to make events accurate according a new vritual tree all events should be unbinded & binded again. And since binding & unbinding are slow it can be time consuming when you need to deal with many events.

Using delegated events, we don't need to take care of this binding/unbinding and the events callbacks used are always up to date. Furthermore for exampe you can set 1000 `onmousemove` in you dom, you won't have further checks than by setting 0 `onmousemove`. It's like a "constant time" to pay which reach its max when you move your mouse like a crazy (I didn't measured the impact, but it doesn't seem that big). React uses this strategy as well as bobril and deku. So it's not perfect on all points but it's imo the best solution around. 

2. Using `props` the events callback are named like this:
```js
props: { onclick: function() {...} }
```
So I tried to use a consistent naming for `events`:
```js
events: { onclick: function() {...} }
```
3. Good catch, fixed in https://github.com/crysalead-js/dom-layer/commit/0c774d53dad32ac36899b566db316f06cd92c9f4

**Comment by justmeandtaken** [comment]
I updated my feedback issue after you read it, check point 3 again.

**Comment by jails** [comment]
Not sure to get the point 3. when an event reach `document.body`, we start bubbling from `event.target` up to `document.body`. As I explained in the previous comment it's not perfect on all points but it's imo the best solution around with a limited overhead impact. I'm not sure to get what you mean but Bobril uses a dedicated function to get the virtual dom node data from a dom element https://github.com/Bobris/Bobril/blob/master/src/bobril.js#L501-551 instead of the `domLayerNode` property (maybe you are talking about an approach like that). But even if DOM element access is a bit slow, I found the current implementation more simple/straightforward.

**Comment by justmeandtaken** [comment]
I'm researching....

Just now I'm trying to figure out why your regex solution is not so happy with **domElementValue**. It throw different things and complain that previous is not found.... 

You are checking for tagName, but what if attrs:{} not set? And a button can be 
```javascript <button type="button">Click Me!</button> ``` with attribute "type" etc. Just now I have a few problems making friends.

**Comment by jails** [comment]
Make a fiddle otherwise I can't help. Btw the tagName here https://github.com/crysalead-js/dom-layer/blob/master/events.js#L13 is related to https://developer.mozilla.org/fr/docs/Web/API/Element/tagName (so it has nothing to do with `attrs`)
